### PR TITLE
TcpServer not abstract, TcpConnection include get

### PR DESCRIPTION
**Pull request by hreintke**
LS,
I took a different approach to create a "bare tcpserver".
Updated the TcpServer class to not to be abstract -> implemented createClient.
Used TcpClient as TcpConnection for that to get to the receive callback.
However : have trouble getting that implemented in tcpserver class. Can you give me a hint/example ?
Also included getRemoteIp and getRemotePort functions in TcpConnection.
But have trouble actually printing them.
Can you look at TcpServer:onClient and give a hint/example on how to display remote IP ?
Herman

### CODE REVIEW

**Comment by anakod** [comment]
Very interesting idea! One problem in merging pull request - you have changed not related sample, you can correct and resend PR, or I can merge it manually.

**Comment by hreintke** [comment]
anakod,
I see that I updated the pull request with a revert and a new commit. The latest commit being the one without the application (=example) updates. What I wanted to do was just sending a new commit but I don't know (yet) how to do that.
Beware, the clientReceive is not yet implemented correctly. 
If you have an example using the TcpClientDataCallback, I will use that for further investigation.
Think there also need to be done some work to get writing done correctly. Working on that too.
Herman

**Comment by anakod** [comment]
I think I can help you with callbacks. To make clear PR just close this and
create new one.
13 апр. 2015 г. 19:37 пользователь "hreintke" <notifications@github.com>
написал:

**Comment by anakod** [comment]
Sorry, you already fixed it, great!

**Comment by hreintke** [comment]
anakod,
OK, I see your callback implementation.
Will work with that later today.
Herman

**Pull request merged**
