### PR TITLE
sync upstream rBoot and Makefile improvements/fixes

### LINKED ISSUE #278: Stability Issues with standalone buil: Makefile for Sming relies on SMING_HOME
As mentioned  in PR #268, I had issues correctly defining SMING_HOME: when sming is installed in a nonstandard location, either the Makefiles has to be modified, or the location has to be injected from outside.
In said PR #268 this caused problems when new include directories where added.

### PR DESCRIPTION
**Pull request by raburton**
don't assume SMING_HOME is defined and correct when compiling Sming itself
adds sdk version  to linker script (like #239)
sync rBoot source with upstream (trivial change)

### CODE REVIEW

**Comment by gernoteger** [comment]
compile works for me, runtime yet to be tested

**Comment by anakod** [comment]
Is it tested on hardware?

**Comment by kireevco** [comment]
How Is it going to work when a project is outside of sming directory?

**Comment by kireevco** [comment]
Actually it should work fine for compiling sming itself.

**Comment by gernoteger** [comment]
I just tested it alongside PR #285, #284. Works nicely on my ESP-12, single-rom layout.

**Comment by gernoteger** [comment]
you can see my testbed here: https://github.com/gernoteger/DobbyESP

**Comment by piperpilot** [comment]
Can we get this merged to the feature branch?

**Comment by raburton** [comment]
>Can we get this merged to the feature branch?

@kireevco is the man we need...

**Comment by kireevco** [comment]
@anakod can merge this too.

@anakod please give certain people merge rights please, @alonewolfx2 and other probably.

**Comment by robotiko** [comment]
@anakod @kireevco please  provide additional merge rights.

**Pull request merged**
