### PR TITLE
+ Deep Sleep functions

### PR DESCRIPTION
**Pull request by alonewolfx2**
+deep sleep and deep sleep set options

### CODE REVIEW

**Comment by anakod** [comment]
Can be named just "sleep" not dsleep or it's name of different mode?

**Comment by alonewolfx2** [comment]
no its different. all modules without rtc, closing in deepsleep mode. sleep modes just affect wifi station.

**Comment by alonewolfx2** [comment]
and module consuming almost 30-50 micro amp in deepsleep mode.

**Comment by anakod** [comment]
Yes, I agree. May be make name like "deepSleep", "setDeepSleepSomething..". Better use single style in naming. And I think what "uint8 option" - hard for end user, better will be have special enum to prevent mistakes (you can look at fileOpen argument as example).

**Comment by anakod** [comment]
Also I make small additional commit for your CPU frequency update, because I think without that users will tring incorrect frequency values.

**Comment by alonewolfx2** [comment]
you are right. can you change that with your style? set options provided in sdk documentation. (0,1,2,4)

**Comment by anakod** [comment]
What sdk documentation you mean?

**Comment by alonewolfx2** [comment]
its in "esp_iot_sdk_v1.0.0\document\English\SDK-Espressif IoT SDK Programming Guide_v1.0.0.pdf"

**Comment by anakod** [comment]
> We can’t automatically merge this pull request.
Why github doesn't alow merging?

**Comment by anakod** [comment]
Ok, I will make it via Path

**Comment by anakod** [comment]
Looks like decalarations aready exist in __USER_INTERFACE_H__

**Comment by anakod** [comment]
Completed! Can you check, please?

**Pull request closed without merging**
