### PR TITLE
Add block read to HardwareSerial

### PR DESCRIPTION
**Pull request by AlmightyFrog**
Feature to read multiple bytes from Serial buffer more efficient.

### CODE REVIEW

**Comment by anakod** [comment]
Can you discover details please. Read direct to memory, yes?

**Comment by AlmightyFrog** [comment]
It's pretty much a combination of how available() and read() uses rxbuf but optimized to use as little overhead as possible for big data.
Looking at it again, there might be slight optimisation, please comment:
- HardwareSerial.cpp:108 is futile as in following line checked again as first condition
- HardwareSerial.cpp:117 is missing brackets as it was c&p from read()
- HardwareSerial.cpp:110, 112, 115 could be comined if requested but should be without effect

I did use this block read trying to make a real transparent UART bridge but failed there getting UDP packets in time - every few seconds lwip just didn't spit out packets anymore (though they were transmitted in time).

**Comment by anakod** [comment]
OK I will look all this points. Next, sorry, I'm not understand, with new method transparent bridge work correctly? Of course String make life easer, but cost additional resources.

**Comment by AlmightyFrog** [comment]
Forget about the point with transparent bridge - i just did want to mention for what i did use this function.

Using String would be a completely different usecase. Idea here is to get as low level as possible the raw data. String would make sense to me only when writing a function like read a complete line or so - but then you have to think about buffer strategy as you can't tell how long a line could be and on embedded systems  resourcs are limited of course.

**Pull request merged**
