### PR TITLE
Missing method for binary frame support

### PR DESCRIPTION
**Pull request by MrAPierce**

### CODE REVIEW

**Comment by robotiko** [comment]
Hi @MrAPierce, 
I tried this patch to see if it would solve  #133, but keeps failing. 
Any hint?
Thanks

**Comment by MrAPierce** [comment]
Hi @robotiko, I have build the SmingFramework project and the HttpServer_WebSockets project successfully with these changes, and tested that the binary frame is working. What keeps failing? building the HttpServer_WebSockets example project or the SmingFramework project?

@anakod could you please test building with these changes also?

**Comment by robotiko** [comment]
Hi @MrAPierce, 
SmingFramework project build without problems, it is just the HttpServer_WebSockets project that fails (the trace is in #133).

**Comment by robotiko** [comment]
Seems that is fixed with latest merge. 

Thanks

**Pull request merged**
