### PR TITLE
rBoot integration and sample

### PR DESCRIPTION
**Pull request by raburton**
Allows building of rBoot itself in-tree. Sample app demonstrates big flash
support, OTA updates and spiffs support. Intended for ESP-12 or similar
device with 4mb of flash (but can be run on anything) where it will give
two 1mb rom slots each with their own 1mb spiffs slot, all updatable with
HTTP OTA.

### CODE REVIEW

**Comment by raburton** [comment]
I really don't know if you'll be interested in this, but this integration and demo project has been several days work with help from members of esp8266.com forum, and was undertaken at their request. I thought it was worth submitting a pull request so you could take a look and see what you think. There are people out there who want to combine the two, but you may not actually want it in Sming, or maybe you'll love it, who knows!

If you aren't familiar with rBoot have a look at [my blog](http://richard.burtons.org/2015/05/18/rboot-a-new-boot-loader-for-esp8266/) from when it was first released. And [this thread](http://www.esp8266.com/viewtopic.php?f=35&t=4288) contains a lot of info about this recent work, probably starting about half way through the thread.

**Comment by avr39-ripe** [comment]
Looks VERY impressive!!!  Cant test it just now, but I vote huge +1 for integrate your great work to sming. Thank you!

**Comment by robotiko** [comment]
++1
Tested prerelease and works great. 
Great contribution to Sming, please merge!. 

Thanks  @raburton

**Comment by kteza1** [comment]
Thanks @raburton for this. Been reading your blogs for the last 5 days. Awesome to have it in Sming

**Comment by alonewolfx2** [comment]
+1 too :) thanks @raburton . i will try it to night.

**Comment by kireevco** [comment]
@raburton thank you so much for your PR. 
We are trying to implement git-flow (#230). Can you please re-submit your PR to a feature branch?
For example _feature/rboot_?

**Comment by raburton** [comment]
How do you do that? I've created a new branch with my changes in it called feature/rboot, but I can't push it to a branch of a matching name in the Sming repo because it doesn't exist there. Do you need to create the branch off master first so I can create the PR against it?

**Comment by kireevco** [comment]
use rboot branch

**Comment by kireevco** [comment]
closed in favour of #253

**Pull request closed without merging**
