### PR TITLE
Merge pull request #1 from anakod/patch-1

### PR DESCRIPTION
**Pull request by j0hncc**
+ Notes about interrupts processing

### CODE REVIEW

**Comment by j0hncc** [comment]
Sorry I am trying to figure out how to pull updates from anakod/Sming into my forked version....

**Comment by ystrem** [comment]
Just commit to your repo.

**Comment by anakod** [comment]
OK, please close this PR if it not used.

**Comment by j0hncc** [comment]
@ystrem, thats the thing, I can't figure out how to "commit to my repo" :)

**Pull request closed without merging**
