### PR TITLE
Use awk to print delta UsedSpace from last to current build

### PR DESCRIPTION
**Pull request by ADiea**
Useful to track the impact of new code. This is how it looks on the console. Note the (+/-delta) from last build.

Memory layout info:
   Section|                   Description| Start (hex)|   End (hex)|Used space
------------------------------------------------------------------------------
      data|        Initialized Data (RAM)|    3FFE8000|    3FFE857D|    1405
    rodata|           ReadOnly Data (RAM)|    3FFE8580|    3FFEA58C|    8204 (+360)
       bss|      Uninitialized Data (RAM)|    3FFEA590|    3FFF4640|   41136 (-8)
      text|            Cached Code (IRAM)|    40100000|    40105E05|   24069 
    irom0_text|           Uncached Code (SPI)|    40209000|    40240F0A|  229130 (+6756)

### CODE REVIEW

**Comment by ADiea** [comment]
This is a cleaned-up and reworked old pull request, originally here https://github.com/anakod/Sming/pull/125

**Comment by kireevco** [comment]
@ADiea Let's be consistent. Please look at this PR that cleans it up and stores platform-specific options in their platform makefiles https://github.com/anakod/Sming/pull/148/
it ends up with one line in the main project file.
```
$(Q) $(MEMANALYZER) $@
```

**Comment by ADiea** [comment]
@kireevco this does not seem to be integrated into sming master yet I was not aware of it. Should I merge 148 with this pr?

**Comment by kireevco** [comment]
@ADiea I would like to wait for @anakod to merge, and then adjust your PR to it. What do you think?

Thank you for your contribution, this is awesome!

**Comment by ADiea** [comment]
@kireevco Sure it's better that way, I subscribed to your PR and will get notified. Cheers

**Comment by anakod** [comment]
I think it can be merged without troubles, because awk already installed with minigw/UDK package.

**Comment by anakod** [comment]
I have checked it and it looks relly very nice!

```
------------------------------------------------------------------------------
Memory layout info:
   Section|                   Description| Start (hex)|   End (hex)|Used space
------------------------------------------------------------------------------
      data|        Initialized Data (RAM)|    3FFE8000|    3FFE8544|    1348
    rodata|           ReadOnly Data (RAM)|    3FFE8550|    3FFE8DC0|    2160 (-40)
       bss|      Uninitialized Data (RAM)|    3FFE8DC0|    3FFF2830|   39536 (-8)
      text|            Cached Code (IRAM)|    40100000|    40105AE9|   23273
irom0_text|           Uncached Code (SPI)|    40209000|    4023637E|  185214 (-12)
Total Used RAM : 43044
Free RAM : 38876
Free IRam : 9513
------------------------------------------------------------------------------
```

**Comment by kireevco** [comment]
@anakod what about my PR? Now it can't be merged https://github.com/anakod/Sming/pull/148

**Pull request merged**
