### PR TITLE
Enabled selection pin for IR send

### PR DESCRIPTION
**Pull request by gustavobreunig**
The IRsend now have a parameter to choose what pin to use, also, removed unused defines.

Before:

```c
IRsend irsend;
```

Now:

```c
IRsend irsend(IR_PIN);
```

### CODE REVIEW

**Comment by kireevco** [comment]
@gustavobreunig I appreciate your PR to _develop_ :) #230 
@gustavobreunig Is this PR backwards-compatible? Will it break old code?

**Comment by gustavobreunig** [comment]
@kireevco 
Yes, it will break old code, I will study something to solve this.
Sorry, I'm new to git, I will do the rebase and another PR in some days.

**Comment by kireevco** [comment]
@gustavobreunig if it will break, do you think you could add backwards-compatibility?
another option, create a feature branch, and test it there. Which option would you prefer?

**Comment by gustavobreunig** [comment]
I think it does not need another branch, it will backwards compatible just with one method overloading.

Now I

**Comment by gustavobreunig** [comment]
@kireevco Done, everything squashed into one commit.

**Comment by kireevco** [comment]
@gustavobreunig I don't think so:


You need to squash all commits to one it and force-push to your fork. It will appear as a single-commit PR here.

**Comment by gustavobreunig** [comment]
@kireevco 
Sorry, I can't figure out how to do, ```git rebase -i 09053eb``` will solve the problem?

**Comment by gustavobreunig** [comment]
Ok, done, learnt something new :)

I'll work on backwards compatible functionality tomorrow.

**Comment by hreintke** [comment]
@gustavobreunig : 
We are cleaning up Sming Repo and PR's.
As I understand the conversation on this PR, it needs some not merged additions for provide backward compatibility. 
Can you describe current status and eventually still needed updates ?

**Pull request merged**
