### PR TITLE
Update NtpClient

### PR DESCRIPTION
**Pull request by hreintke**
Use UDPClient instead of UDPServer
Add fuctionality to :
- use timezone
- If no callback, set systemtime in ntpclient
- wait until wifi connected
- use both NTP_VERSION 4 and 3 answers

### CODE REVIEW

**Comment by anakod** [comment]
I think it's not very obviously what we will set system clock only if callback isn't set. Maybe add description or some other way to make it simpler?

**Comment by hreintke** [comment]
I understand your remark, by description you mean documentation ?
The ratio behind only when callback is not set is 
-  if a user sets callback he/she want control on what is happening so only callback
- if no callback, "normal behaviour" of ntp is to keep time in sync -> so set systemtime

**Comment by danielnilsson9** [comment]
Maybe it would be more clear if having a method on the SystemClock instead, perhaps "setAutoSyncWithNtp(bool enable)" or something which would set up auto syncing using the NTP class? Then the user wouldn't even have to create the NtpClient to have autosyncing time. And maybe the timezone method could be moved there aswell then. Just a thought.

**Comment by hreintke** [comment]
@danielnilsson9 : My idea was indeed to make the usage as simple as possible. 
(now implemented) Just instantiate ntpclient with your preferences on server, freq and TZ and your done keeping time in sync. Moving (part of ) that to SystemClock is definitely an option

**Comment by anakod** [comment]
1. Move timezone information in clock - great idea. Like in .NET we have two properties: Now and UtcNow. Also that mehods should return DateTime, not uint.
2. I think that the methods should be assigned to who carries out the action, so may be add to ntpclient  method setAutoUpdateSystemClock(bool) ? Ans set it by default depending on the callbac parameters and etc.

**Comment by danielnilsson9** [comment]
@anakod Sound good to me!

@hreintke While you are at it working with these classes:
- The NtpClient should probably also be updated with those nice Delegate callbacks. 
- A workaround for issue #67 would be easy to implement, with a e.g. a callback every 60 seconds and then a counter to se if it is time to update.

**Comment by hreintke** [comment]
OK, Will work on it and come with an updated proposal

**Comment by hreintke** [comment]
@anakod : Are you sure you want now() and the new utcnow() to return DateTime ?
As far as I understand, all arduino/esp use the time_t = uint as return value.
Of course we can add methods like nowdt and utcnowdt (or any name you prefer) to provide DateTime results but then we keep sming compatible to arduino/esp

**Comment by tprochazka** [comment]
I think that now() should always return time as time_t in the UTC, as as seconds since Jan 1 1970
But possibility to get local time as DateTime should be very ussefull.
Arduino has also great library which can handle automatically timezone change for summer and winter time: https://github.com/JChristensen/Timezone which contain Timezone classwith method toLocal() which is able to convert utc now() to local time.

**Comment by hreintke** [comment]
@anakod : made updates in the way you suggested (I think).
Needs some updates and cleaning of code but shows the direction/options.
Is this the way to go ?
@tprochazka : I had seen the TimeZone lib. First want to make a simple version before (possible) go for a fullblown version.

**Comment by anakod** [comment]
> I think that now() should always return time as time_t in the UTC
1. Why not DateTime object? (it's more flexible)
2. Why in UTC?

I'like .NET architecture, but of course, it has many details related to that functionality.

**Comment by hreintke** [comment]
@anakod : 
DateTime vs Time_t : In arduino everyone is using the fucntion now() which there is returning time_t.
If you want compatibility with that you need to return time_t and make additional other options.
In my latest update I user uint32_t as you did.
UTC : I was wrong in that. in the latest update now() returns localtime and I added the option to call now(bool reqUtc). so both options are available

**Comment by anakod** [comment]
Converting DateTime to time_t can be automatic (implicit convesrsion).

**Comment by hreintke** [comment]
OK, have done some initial reading on implicit conversion.
Am I correct that adding something like "operator int() { return toUnixTime(); }"' to the public part of DateTime class is the way you are thinking ?
If so I check/test further with that

**Comment by anakod** [comment]
Yes, it is "operator time_t()"

**Comment by hreintke** [comment]
OK, will work in that direction.

**Comment by anakod** [comment]
Also, as example of implicit conversion, you can look IPAddress class too.

**Comment by hreintke** [comment]
Next version of ntpclient, systemclock and datetime.
Is this the direction you envisioned ?
Can you have a look at the systemclock setNtpSync ?
I used two options in application.cpp (identical in my view) 
	SystemClock.setNtpSync("fritz.box",30);
//	nt = new NtpClient("fritz.box",30);
both use the same ntpclient way of working but I get system crashes using the systemclock implementation

**Comment by anakod** [comment]
I think you just fogot initialize "ntpClient" clock class property, and it isn't null by default (and it trying to delete wrong pointer).

Also, two version with delegates and methods callbacks isn't needed here (we provide two callback ways in Timer class for high frequency timers and perfomance), but it isn't problem at all, just case.

Thank you for great work! You will fix setNtpSync method problem or I should?

**Comment by hreintke** [comment]
@anakod : I think ntpClient is initialized by : 	NtpClient* ntpClient = nullptr; in SystemClock.h 
If you can have a look at setNtpSync would be great, I am stuck and out of ideas at the moment.
Otherwise I leave out the systemclock sync option and only implement the ntpclient version, but am a little reluctant to that because we might have a undiscovered issue in that.

For the delegated and callback both implemented : I agree on just having delegates.
I just wanted to create a constructor like : 
NtpClient(String reqServer, int reqIntervalSeconds, NtpTimeResultCallback onTimeReceivedCb)
 : NtpClient(reqServer, reqIntervalSeconds, Delegate<void(time_t ntptime)> (onTimeReceivedCb))
and only use delegates in NtpClient but didn't find the right syntax yet (lack of c++ knowledge from my side), same is for a nice typedef for delegates.
So decided for this intermediate version to keep both

**Comment by tprochazka** [comment]
Only example is now completely confusing.

**Pull request merged**
