### PR TITLE
Added Delegate support for the Station::waitConnection method.

### PR DESCRIPTION
**Pull request by slaff**

### CODE REVIEW

**Comment by anakod** [comment]
We can remove old c-style callbacks methods, because Delegates already cover this functionality and provide back compatibility.

**Comment by slaff** [comment]
> Delegates already cover this functionality and provide back compatibility.

@anakod Cool! Is there an example how to turn normal C-style function into delegate? For example I have the following:

```CPP
typedef Delegate<void(int,int)> XDelegate;

void ClassName::doSomeWork(XDelegate xDelegate)
{
     xDelegate(1,2);
}
```

How can I  use: 

```CPP
void xCallback(int a, int b)
{
  //...
}

ClassName obj;

obj.doSomeWork(???? xCallback ???)
```

**Comment by anakod** [comment]
obj.doSomeWork(xCallback);

**Comment by slaff** [comment]
Nice! That means that there is a need for general refactoring of all methods/functions that accept callbacks :)

**Comment by anakod** [comment]
Yes, it is. Part of them already refactored.

**Comment by slaff** [comment]
@anakod Can you check if this refactoring will work?

**Pull request merged**
