### PR TITLE
Added working example of Delegate Callback

### PR DESCRIPTION
**Pull request by hreintke**
Updates SystemClock to use enums

### CODE REVIEW

**Comment by hreintke** [comment]
@anakod : 
Now with working example of delegate callback
Is there a specific reason you made the callback function returning bool ? If not, maybe we should change to void.
When using the ntpClientdemo class in the example I found that a declaration of 
ntpClientDemo dm1 = ntpClientDemo(); is working correctly but 
ntpClientDemo dm1();  is not working.
I expected both being the same : Do you have an explanation for that ?
Still working on getting the ntpClient internally ony working with delegate, no luck in that at the moment. 
Can you point into a direction I should update 
```NtpClient::NtpClient(String reqServer, int reqIntervalSeconds, NtpTimeResultCallback onTimeReceivedCb)
 : NtpClient(reqServer, reqIntervalSeconds, NtpClientResultCallback (onTimeReceivedCb))
```
in order to move static callback to delegate callback ?

**Comment by anakod** [comment]
> Is there a specific reason you made the callback function returning bool ? If not, maybe we should change to void.

It isn't my code, but I think yes, it can be changed.

> ntpClientDemo dm1(); is not working.
It depended on constructor, but should work, I think.

**Comment by hreintke** [comment]
'''
ntpClientDemo dm1 = ntpClientDemo(); is working correctly but
ntpClientDemo dm1(); is not working
'''
I expected in both options above the same constructor would be used. Is that correct ?

**Comment by anakod** [comment]
```C++
ntpClientDemo &dm1 = ntpClientDemo();
ntpClientDemo dm1();
```
- this lines should be equals, I think. In your example - no.

**Comment by hreintke** [comment]
If I use 
```
ntpClientDemo &dm1 = ntpClientDemo();
```
I get the compile time error 
```
app/application.cpp:56:36: error: invalid initialization of non-const reference of type 'ntpClientDemo&' from an rvalue of type 'ntpClientDemo'
 ntpClientDemo &dm1 = ntpClientDemo();
```
When using 
```
ntpClientDemo dm1();
```
It looks like no instantiation at all.
If you can think of something please let me know. Next steps from me on thursday

**Pull request merged**
