### PR TITLE
:beetle:Fix isInputPin reversed logic

### PR DESCRIPTION
**Pull request by ADiea**
+ fix stupid inverted logic issue on isInputPin oops 
+ make digitalWrite() function with single return point

### CODE REVIEW

**Comment by ADiea** [comment]
@anakod this is *urgent* pull request dunno how it escaped me, I still had pullup() calls in my code and this got unobserved

**Comment by anakod** [comment]
Did you complete hardware tests?

**Comment by ADiea** [comment]
@anakod yes hw test passed I have data from DHT22 device. 
If i remove pullup from DHT code, without this modification won't work
Also in my code I did not return in digitalWrite so for outputs pullup was activated == nop and then the write works but if you activate pullup and then return output will no longer work.
Rootcause isInputPin has reversed logic...

**Comment by ADiea** [comment]
thanks!

**Pull request merged**
