### PR TITLE
CommandHandler : separate command registration

### PR DESCRIPTION
**Pull request by hreintke**

### CODE REVIEW

**Comment by hreintke** [comment]
@anakod : Don't know why the updates came into the PR twice and how to delete one of them.
Can you work with this as is or do I need to resubmit the PR

**Comment by anakod** [comment]
Sorry, what you mean?

**Comment by hreintke** [comment]
Above in the PR I see two lines : 
CommandHandler : separate command registration
Merge branch 'Command_Begin' of C:/Users/Herman/git/Sming_Anakod_0714… 
The content of those is the same

**Comment by anakod** [comment]
I think it's just branch merging. List of actual changes you can see here in "Files changed" tab.

**Comment by anakod** [comment]
Did this P-R cover https://github.com/anakod/Sming/pull/169 functionality, or it is separated?

**Comment by hreintke** [comment]
Yes, This is just the #169. I made a specific PR for that so that it can be included now and not have to wait on other CommandProcessor activities

**Comment by anakod** [comment]
Great, thank you.
@ADiea can you look memory usage, please?

**Comment by ADiea** [comment]
i will try tonight
thanks

**Pull request merged**
