### PR TITLE
file system problem

### PR DESCRIPTION
**Pull request by alonewolfx2**
if we test some other project like meteocontrol and upload http server bootstrap again , sometimes the other files missing. so we must to check all files.

### CODE REVIEW

**Comment by anakod** [comment]
Greetings! Very glad to your participation.
I have some questions:
1) In start procedure i was checking only last file, so if it was exist, all other files should be available too. It's not enough?
2) Can you explain details of bug what you found?
3) May be, if we check all files and always start one action, will be better to combine all this cases to one branch?

**Comment by alonewolfx2** [comment]
you are right. 
let me explain. i flashed httpbootstrap example and esp8266 download all files with first boot. everything ok than i flashed blink examples and than i flashed meteocontrol examples. my dsl connection down and esp8266 fail. and than i flashed httpbootstrap again. i tried webserver and tadaa, 404 not found. serial says index.html notfound. i flashed again. serial says webserver started but i am getting 404 notfound on chrome and serial says index.html notfound. module checked jquery file and jquery file exist. webserver started without index.html

**Comment by anakod** [comment]
Agree, thank you!

**Comment by anakod** [comment]
We should make check like this in HttpServer_Bootstrap also, yes?

**Comment by alonewolfx2** [comment]
agree. and maybe can add file.list api like nodemcu.

**Comment by anakod** [comment]
Yes, it should be good idea! Not sure is it implemented in spiffs?

**Comment by alonewolfx2** [comment]
i dont know but is it implemented in spiffs but nodemcu using same spiffs and it can list files :)

**Comment by anakod** [comment]
nodemcu using fork of original library, but it shouldn't be a problem.

**Pull request merged**
