### PR TITLE
Initial Debug implementation

### PR DESCRIPTION
**Pull request by hreintke**
This is an initial implementation.
I needed some way to be able to redirect debug output to my upcoming telnet server.
Decided to make a generic solution for that, not yet fully tested.

Will add some more functionality, like debuglevels and a user choice for the state of debug when esp starts.

Please comment

### CODE REVIEW

**Comment by anakod** [comment]
@hreintke sorry, I'm still thinking about this feature. I'll provide my ideas soon, most of that implementaton is fine for our final solution.

**Comment by hreintke** [comment]
@ankod, no problem, I was busy with other things also.
I just committed the next steps, it includes a refactoring and initial debug level printf.
It uses variadic templates, what is your opinion about that ?

I have had the Debug.lprintf(loglevel, "formastring",...) working but broke something in making it cleaner, now I get undefined reference when using, If you know why, happy to hear from you.
the lprintf2, which is identical but not part of the DebugClass works as expected.
this is how I use it now in application : 
```
//	Debug.lprintf(0,"test %d",helloCounter);
	lprintf2((helloCounter % 2),"test %d",helloCounter);
```

Another thing to think about is user_config.h.
Maybe we should have a "global" user_config with default values for all configurable items and have the application user_config only override the ones they want.

**Comment by hreintke** [comment]
Now debug.lprintf implemented in debug.h, works as expected, see basic serial example.
Must be something obvious what I am overlooking

**Comment by hreintke** [comment]
Now fairly complete, will check further in the coming days.

**Comment by hreintke** [comment]
Can't get (yet) anymore commits in this PR.
Please update : 
Debug.setDebug(Serial)
to : 
Debug.setDebug(DEBUG_DEFAULT_OUTPUT,DEBUG_DEFAULT_PREFIX,DEBUG_DEFAULT_START);
in user_main.cpp

**Comment by kireevco** [comment]
@hreintke Can you please give more info what would be the way to use it? Will it start a telnet server?

**Comment by hreintke** [comment]
@kireevco : No my ideais not to let it start a telnetserver, but DebugClass has the option to have the debug stream redirected. I am working on a telnetserver, which, when a client connects "calls" the DebugClass to redirect the stream to itself and when the client closes, redirect back to (now) default or (later) to previous value.

**Comment by kireevco** [comment]
Still confused. Where do we see actual debug text? Are we connecting to
device over telnet?
Is this like that: On telnet connect event serial output stream gets
redirected to a telnet tty? Is that about right?

On Tuesday, June 23, 2015, hreintke <notifications@github.com> wrote:

> @kireevco <https://github.com/kireevco> : No my ideais not to let it
> start a telnetserver, but DebugClass has the option to have the debug
> stream redirected. I am working on a telnetserver, which, when a client
> connects "calls" the DebugClass to redirect the stream to itself and when
> the client closes, redirect back to (now) default or (later) to previous
> value.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anakod/Sming/pull/115#issuecomment-114752259>.
>


-- 
--
Sincerely,
 Dmitry Kireev
 cel.: +1 (818) 850-5577
 email, gtalk: dmitry@kireev.co
<dmitry@kireev.co> skype: kireev.co
 aim: 336719228

**Comment by hreintke** [comment]
Yes, that's the way I am implementing. 
When the telnetserver is started and a someone connects, the debugoutput is redirected to the telnet.
There would then also be the option to "only get debug output when a telnet is connected" so it would "free the serial" almost complete from debugoutput

**Comment by kireevco** [comment]
This is really good, I like it!

On Wednesday, June 24, 2015, hreintke <notifications@github.com> wrote:

> Yes, that's the way I am implementing.
> When the telnetserver is started and a someone connects, the debugoutput
> is redirected to the telnet.
> There would then also be the option to "only get debug output when a
> telnet is connected" so it would "free the serial" almost complete from
> debugoutput
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anakod/Sming/pull/115#issuecomment-114754291>.
>


-- 
--
Sincerely,
 Dmitry Kireev
 cel.: +1 (818) 850-5577
 email, gtalk: dmitry@kireev.co
<dmitry@kireev.co> skype: kireev.co
 aim: 336719228

**Comment by hreintke** [comment]
My general idea was that, together with OTA and another extension tbd  to be able to send/process usercommands (debug on/off, restart,...) it would give a (almost) full remote controllable device.

**Comment by AlmightyFrog** [comment]
Hmm, some people might not like that auto select approach. Best would be if we could make it in source code selectable:
- uart only
- telnet only
- auto (uart if telnet not connected, otherwise telnet)

**Comment by hreintke** [comment]
@AlmightyFrog : The DebugClass (now) doesn't enforce an auto select, it merely implements the option to redirect to any stream/delegate. In telnet implementation (other PR) we can then implement several options to handle (re)directing debugoutput automatic or by issuing debug command.

**Comment by anakod** [comment]
You want update it before merging, yes?

**Comment by hreintke** [comment]
@anakod : Yes. I will we off until wednesday but end off next week I will have an updated version.

**Comment by ADiea** [comment]
@all 
Would you also consider a compile-time based logging system ? I'm currently working on a old style LOG_I() LOG_E() LOG_W() macros that get removed from code depending on -D option in makefile. For me this makes sense on a small ram/rom device  but I also like this runtime debug class

**Comment by hreintke** [comment]
@ADiea : First thought is that that LOG.. macros are still possible with the Debug Class.
If they "define" something like Debug.printf(level, type, formatstring,...). Will be working on functionality of the debugclass the coming days.
Then we would have both worlds implemented.
However Anakod does not prefer "macro magic" so it's also to him

**Comment by hreintke** [comment]
Replaced by #195

**Pull request closed without merging**
