### PR TITLE
Websocket Client

### PR DESCRIPTION
**Pull request by hrsavla**
Resubmitting Websocket Client  files as per git flow.

### CODE REVIEW

**Comment by kireevco** [comment]
@hrsavla This looks great!

**Comment by robotiko** [comment]
@hrsavla 
Is there any pending details to consider?
is it tested?
what is missing to be merged?

**Comment by hrsavla** [comment]
I am busy with other work. I will look into it again on Saturday.

Hemant Savla

**Comment by robotiko** [comment]
Hi @hrsavla, 
any update? is just waiting for testing (more people can help) or needs some refacts?

**Comment by piperpilot** [comment]
I was going to test this, but I can't find the feature/websocket-client branch.  Am I missing something or has it been deleted?

**Pull request merged**
