### PR TITLE
Replace ${ESP_HOME}/sdk/include with ${ESP_HOME}/ESP8266_SDK/include

### PR DESCRIPTION
**Pull request by ozayturay**
Replace ${ESP_HOME}/sdk/include with ${ESP_HOME}/ESP8266_SDK/include in .cproject files to prevent warnings in Eclipse

### CODE REVIEW

**Comment by anakod** [comment]
As I know, it's a problem, because in Open SDK (linux, mac) this pacth are different.
May be we can add both paths without conflicts?

**Comment by ozayturay** [comment]
Isn't .cproject file Eclipse specific?

**Comment by anakod** [comment]
No, it is the same for all platforms.

**Comment by ozayturay** [comment]
Does Linux and Mac guys use Eclipse too, or do they prefer command line?

Then the solution is renaming or symlinking ESP8266_SDK to sdk in C:\Espressif right?

**Comment by anakod** [comment]
Yes, them use.
May be we can just add both paths? Will it provide errors?

**Comment by anakod** [comment]
Also please update, new project was added :)

**Comment by ozayturay** [comment]
I'll try to add both anc check if Eclipse gives warnings, but i guess it will. I'll let you know. :)

**Comment by ozayturay** [comment]
Putting both paths in .cproject file gives warnings. The reasonable solution is renaming ESP8266_SDK folder to sdk in C:\Espressif folder. It can break makefiles in Espressif/examples though.

**Comment by anakod** [comment]
Which warnings it provide? Can we make some workaround?

**Comment by kireevco** [comment]
When you install sdk via chocolatey it creates a symlink automatically. Same happens when you update it.

**Pull request closed without merging**
