### PR TITLE
Cpu frequency update

### PR DESCRIPTION
**Pull request by zhivko**

### CODE REVIEW

**Comment by anakod** [comment]
Hello. Please, cancel this pull-request

**Comment by kireevco** [comment]
@zhivko too many file changes that are not related to the PR.
Please make it clear what exactly your are adding and resubmit PR.
Closing for now.

**Comment by zhivko** [comment]
OK, was a bad try...

**Comment by kireevco** [comment]
We really appreciate your contributions!

**Comment by anakod** [comment]
@zhivko we are really love every commit. We want to make great solution together, thank you for appreciate Sming.

**Pull request closed without merging**
