### PR TITLE
SDCard integration

### PR DESCRIPTION
**Pull request by ADiea**
This is work in progress, I'm currently working on the example project - but we can discuss on it.

Some points 
* My hardware uses other GPIO pins so that hardware SPI is not an option for me. That is why I have implemented a software SPI class that the sdcard uses.
* FAT filesystem is used, the ChaN implementation (http://elm-chan.org/fsw/ff/00index_e.html)

### CODE REVIEW

**Comment by ADiea** [comment]
Added simple example to write 1024 bytes and measure the write speed

**Comment by lopelex** [comment]
+1

**Comment by robotiko** [comment]
+1

**Comment by alonewolfx2** [comment]
I was waiting for it. thanks @ADiea

**Comment by ADiea** [comment]
@alonewolfx2 I've added a write benchmark example. It uses fopen, fclose, fwrite. The rest are the the usual fread, f_lseek etc you can see their prototypes in /SmingCore/Services/

Please be aware that in order to keep the code short, I used _FS_MINIMIZE == 2 in Sming\Sming\Services\FATFS\ffconf.h => this is the resulting functions available

```
FRESULT f_open (FIL* fp, const TCHAR* path, BYTE mode);				/* Open or create a file */
FRESULT f_close (FIL* fp);											/* Close an open file object */
FRESULT f_read (FIL* fp, void* buff, UINT btr, UINT* br);			/* Read data from a file */
FRESULT f_write (FIL* fp, const void* buff, UINT btw, UINT* bw);	/* Write data to a file */
FRESULT f_lseek (FIL* fp, DWORD ofs);								/* Move file pointer of a file object */
FRESULT f_sync (FIL* fp);											/* Flush cached data of a writing file */
FRESULT f_mount (FATFS* fs, const TCHAR* path, BYTE opt);			/* Mount/Unmount a logical drive */
'''

**Comment by alonewolfx2** [comment]
you are right. but another small example can be helpful for new users. arduino ide has file list,sd info,etc sample sketch as you know. this is just a suggestion for new users

**Comment by ADiea** [comment]
@alonewolfx2 You are right I will try to use some interesting functions

Meanwhile I extended the available functions with no size cost (as long as you don't use the functions:) )

```
FRESULT f_open (FIL* fp, const TCHAR* path, BYTE mode);				/* Open or create a file */
FRESULT f_close (FIL* fp);											/* Close an open file object */
FRESULT f_read (FIL* fp, void* buff, UINT btr, UINT* br);			/* Read data from a file */
FRESULT f_write (FIL* fp, const void* buff, UINT btw, UINT* bw);	/* Write data to a file */
FRESULT f_lseek (FIL* fp, DWORD ofs);								/* Move file pointer of a file object */
FRESULT f_truncate (FIL* fp);										/* Truncate file */
FRESULT f_sync (FIL* fp);											/* Flush cached data of a writing file */
FRESULT f_opendir (DIR* dp, const TCHAR* path);						/* Open a directory */
FRESULT f_closedir (DIR* dp);										/* Close an open directory */
FRESULT f_readdir (DIR* dp, FILINFO* fno);							/* Read a directory item */
FRESULT f_mkdir (const TCHAR* path);								/* Create a sub directory */
FRESULT f_findfirst (DIR* dp, FILINFO* fno, const TCHAR* path, const TCHAR* pattern);	/* Find first file */
FRESULT f_findnext (DIR* dp, FILINFO* fno);							/* Find next file */
FRESULT f_unlink (const TCHAR* path);								/* Delete an existing file or directory */
FRESULT f_rename (const TCHAR* path_old, const TCHAR* path_new);	/* Rename/Move a file or directory */
FRESULT f_stat (const TCHAR* path, FILINFO* fno);					/* Get file status */
FRESULT f_chmod (const TCHAR* path, BYTE attr, BYTE mask);			/* Change attribute of the file/dir */
FRESULT f_utime (const TCHAR* path, const FILINFO* fno);			/* Change times-tamp of the file/dir */
FRESULT f_getfree (const TCHAR* path, DWORD* nclst, FATFS** fatfs);	/* Get number of free clusters on the drive */
FRESULT f_mount (FATFS* fs, const TCHAR* path, BYTE opt);			/* Mount/Unmount a logical drive */
int f_putc (TCHAR c, FIL* fp);										/* Put a character to the file */
int f_puts (const TCHAR* str, FIL* cp);								/* Put a string to the file */
int f_printf (FIL* fp, const TCHAR* str, ...);						/* Put a formatted string to the file */
TCHAR* f_gets (TCHAR* buff, int len, FIL* fp);						/* Get a string from the file */
```

**Comment by alonewolfx2** [comment]
ok i am waiting to new commit :)

**Comment by alonewolfx2** [comment]
what do you think about sdcard webserver example ?

**Comment by ADiea** [comment]
@alonewolfx2 I guess we could do that by implementing some functions in the webserver that use the SDCard filesystem or maybe extend the current functions and when a file is not found in spiff maybe search for it on the sdcard if it is initialised. - but that is work for some other time :)

@all improved example, show usage of common functions to read/write/list files/get file properties etc
see Sming\SDCard\example.output.txt

i think it's ready for merge

**Comment by alonewolfx2** [comment]
@ADiea sounds good. please join us on gitter.
https://gitter.im/alonewolfx2/Sming

**Comment by ADiea** [comment]
@anakod do you agree with mergeing, or do you have any objections to the code? Thanks

**Comment by anakod** [comment]
I think it's OK. Is all right with copyrights here?

**Comment by ADiea** [comment]
First of all the author states this here: http://elm-chan.org/fsw/ff/en/appnote.html under _About FatFs License_

```
Therefore FatFs license is one of the BSD-style licenses but there is a significant feature. FatFs is mainly intended for embedded systems. In order to extend the usability for commercial products, the redistributions of FatFs in binary form, such as embedded code or any forms without source code, does not need to explain about use of FatFs in the documentations. This is equivalent to the 1-clause BSD license. Of course FatFs is compatible with the most open source software licenses including GNU GPL. When you redistribute the FatFs source code with any modification or create a fork, the license can also be changed to GNU GPL, BSD-style license or any open source software licenses that not conflict with FatFs license.
```

Secondly, license info file-by-file

* Sming/Libraries/SDCard/SDCard.cpp
  Copyright (C) 2013, ChaN, all right reserved.
  This software is a free software and there is NO WARRANTY.
  No restriction on use. You can use, modify and redistribute it for
  personal, non-profit or commercial products UNDER YOUR RESPONSIBILITY.

* Sming/Services/FATFS/diskio.h
  Low level disk interface modlue include file   (C)ChaN, 2014
  no explicitly stated copyright but it's on the same project as the first, it is the corresponding .h file
  
* Sming/Services/FATFS/ff.h
  seems MIT compatible = must retain copyright notice + disclamer software provided as is
  
* Sming/Services/FATFS/ffconf.h
  no explicitly license stated but assumed the same as the cpp file 
  
* Sming/Services/FATFS/integer.h
  no author or license information
  
* Sming/Sming/Services/FATFS/ff.c
  same as ff.h
  
Thirdly, my files are provided under MIT: 
* use without restrictions for commercial and personal projects
* maintain copyright notice, credit author
* "provided as-is" disclaimer

**Comment by anakod** [comment]
Great, thank you

**Comment by anakod** [comment]
Last question: why you are using Software SPI instead of Hardware (which should be much faster)?
Is it possible to work with both (with user choice)?

**Comment by ADiea** [comment]
On my board the hardware SPI pins are tied to other devices. 
It is not possible to work with both SPIs. 

Regarding SPI speed, at SDCard initialization a slow 400Kbps speed must be used after that 1-2 Mhz must be used in SDCard SPI mode. Most SDcards do not support higher speeds in the SPI mode anyway

**Comment by anakod** [comment]
Ok, agree, but I think hardware SPI will be very good option too.

**Comment by ADiea** [comment]
I hope someone has a scope to measure the soft and hw spi speeds it would be nice to get a clearer picture

agreed, maybe implementing a spi partent from which hardware and software spi classes would inherit

**Comment by mopac** [comment]
> 
> 
> @alonewolfx2 I guess we could do that by implementing some functions in the webserver that use the SDCard filesystem or maybe extend the current functions and when a file is not found in spiff maybe search for it on the sdcard if it is initialised. - but that is work for some other time :)
> 
> @ALL improved example, show usage of common functions to read/write/list files/get file properties etc
> see Sming\SDCard\example.output.txt
> 
> i think it's ready for merge

I know it is an old post, but did anyone do anything regarding webserver serving files from SD Card?

Ray

**Pull request merged**
