### PR TITLE
Improve COM port configs, terminal when building

### PR DESCRIPTION
**Pull request by kireevco**
Change default COM_PORT for linux (to be compatible with Docker) & move ports higher in Makefiles
Move default COM port setting higher in Make Files
Change com port default speed (SERIAL_BAUD_RATE=115200 in code)
Improve cross-plattform KILL_TERM and MEMANALYZER

Video: http://screencast.com/t/KfVmGXxyGPQ

### CODE REVIEW

**Comment by kireevco** [comment]
Just wondering if there is anything else I need to add to get this merged?

**Comment by alon24** [comment]
+

**Comment by anakod** [comment]
Thank you very much!

**Comment by kireevco** [comment]
Yesssssssss

Thank you!

**Pull request merged**
