### PR TITLE
Feature/temperature ds1820 delay

### PR DESCRIPTION
**Pull request by flexiti**
to meet the ESP8266 requirements for use of the Delay() function
 See #249

### CODE REVIEW

**Comment by flexiti** [comment]
Resubmit,
It is well published now?

**Comment by kireevco** [comment]
@flexiti yes, that's the idea.

**Comment by Tavalin** [comment]
Just noticed a slight typo in the method call "DoMesure".

**Comment by flexiti** [comment]
@Tavalin 
thanks,
 it is internal method name and does not affect the operation, so I will wait a little bit, maybe something else needs to be change - it can be improved together

**Comment by flexiti** [comment]
@kireevco 
You have created a special, separated branch for this, but even from there you can not get this :) How to test? a long way..

**Comment by kireevco** [comment]
What do you mean?

**Comment by flexiti** [comment]
if I open branch "feature/Temperature_DS1820-delay" ,I do not see the changes that have published. why?

**Comment by kireevco** [comment]
@flexiti because your PR is still open. Let's merge your changes to the branch.

**Comment by avr39-ripe** [comment]
So for change in feature/* branch to be merged in this feature/* branch one must close initial PR? or what? My feature/miniterm* is is similar state, PR opened, no changes in corresponding branch..
thanks!

**Comment by flexiti** [comment]
Now I can see it, but I did't do anything.
Does it mean that PR must be approved by someone who has permissions?
If so, in future branch should be done fairly quickly, otherwise no one else can test it.

Second question about "Delete branch" button I have visual now.
It is :  finish this branch, and move all do develop branch,      or delete this branch  ?

**Comment by kireevco** [comment]
Yes, the goal is to streamline that, so it will be very quick. When you are done with testing in a branch, we need a pr to merge it to develop.

Again, next time just submit pr against develop branch, if the feature is very big and breaks or can break everything we'll move it to A feature branch. That should have much less friction in the beginning. Does that sound good?:)

**Comment by flexiti** [comment]
Yes, its ok :)

**Pull request merged**
